name: filepicker_windows
description: |
  A plugin that uses FFI to offer file selection in Windows using the modern 
  common item dialog box.
version: 2.0.5
repository: https://github.com/timsneath/filepicker_windows
issue_tracker: https://github.com/timsneath/filepicker_windows/issues

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  ffi: ^2.0.0
  win32: ^4.0.0

dev_dependencies:
  lints: ^2.1.0

topics:
  - windows
  - ffi
  - desktop