name: filepicker_windows_example
description: Demonstrates how to use the filepicker_windows package.
publish_to: 'none'

environment:
  sdk: '^3.1.0'

dependencies:
  filepicker_windows:
    path: ../../
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  win32: ^5.0.7
  path_provider_windows: ^2.2.1

flutter:
  uses-material-design: true

dev_dependencies:
  dartwindows_lints: ^1.0.0
